version: 0.2

phases:
  build:
    commands:
      - echo "Building Docker images for all services..."
      - docker build -t 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameAuth:latest -f ./backend/auth/Dockerfile ./backend/auth
      - docker build -t 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameFavorite:latest -f ./backend/favorite/Dockerfile ./backend/favorite
      - docker build -t 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNamePerformance:latest -f ./backend/performance/Dockerfile ./backend/performance
      - docker build -t 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameSearch:latest -f ./backend/search/Dockerfile ./backend/search
      - docker build -t 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameSurvey:latest -f ./backend/survey/Dockerfile ./backend/survey


      - echo "Pushing Docker images to ECR..."
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameAuth:latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameFavorite:latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNamePerformance:latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameSearch:latest
      - docker push 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com/$ImageNameSurvey:latest


      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f ./k8s/auth-deployment.yaml
      - kubectl apply -f ./k8s/auth-service.yaml
      - kubectl apply -f ./k8s/favorite-deployment.yaml
      - kubectl apply -f ./k8s/favorite-service.yaml
      - kubectl apply -f ./k8s/performance-deployment.yaml
      - kubectl apply -f ./k8s/performance-service.yaml
      - kubectl apply -f ./k8s/search-deployment.yaml
      - kubectl apply -f ./k8s/search-service.yaml
      - kubectl apply -f ./k8s/survey-deployment.yaml
      - kubectl apply -f ./k8s/survey-service.yaml


artifacts:
  files:
    - '**/*'
