version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 205930629963.dkr.ecr.ap-northeast-2.amazonaws.com
      - aws ecr create-repository --repository-name ticket101-ecr
      - echo "Downloading Kubernetes manifests from S3..."
      - aws s3 cp s3://ticket101-env-files/k8s/auth/auth-deployment.yaml ./auth-deployment.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/auth/auth-service.yaml ./auth-service.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/favorite/favorite-deployment.yaml ./favorite-deployment.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/favorite/favorite-service.yaml ./favorite-service.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/performance/performance-deployment.yaml ./performance-deployment.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/performance/performance-service.yaml ./performance-service.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/search/search-deployment.yaml ./search-deployment.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/search/search-service.yaml ./search-service.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/survey/survey-deployment.yaml ./survey-deployment.yaml
      - aws s3 cp s3://ticket101-env-files/k8s/survey/survey-service.yaml ./survey-service.yaml

  build:
    commands:
      - echo "Applying Kubernetes manifests..."
      - kubectl apply -f ./auth-deployment.yaml
      - kubectl apply -f ./auth-service.yaml
      - kubectl apply -f ./favorite-deployment.yaml
      - kubectl apply -f ./favorite-service.yaml
      - kubectl apply -f ./performance-deployment.yaml
      - kubectl apply -f ./performance-service.yaml
      - kubectl apply -f ./search-deployment.yaml
      - kubectl apply -f ./search-service.yaml
      - kubectl apply -f ./survey-deployment.yaml
      - kubectl apply -f ./survey-service.yaml

  post_build:
    commands:
      - echo "Deployment completed. Cleaning up local files..."
      - rm -f ./auth-deployment.yaml ./auth-service.yaml
      - rm -f ./favorite-deployment.yaml ./favorite-service.yaml
      - rm -f ./performance-deployment.yaml ./performance-service.yaml
      - rm -f ./search-deployment.yaml ./search-service.yaml
      - rm -f ./survey-deployment.yaml ./survey-service.yaml

artifacts:
  files:
    - '**/*'
