version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  survey:
    build:
      context: ./survey
      dockerfile: Dockerfile
    env_file:
      - ./survey/.env
    ports:
      - "${SURVEY_PORT}:${SURVEY_PORT}"
  
  favorite:
    build:
      context: ./favorite
      dockerfile: Dockerfile
    env_file:
      - ./favorite/.env
    ports:
      - "${FAVORITE_PORT}:${FAVORITE_PORT}"

  performance:
    build:
      context: ./performance
      dockerfile: Dockerfile
    env_file:
      - ./performance/.env
    ports:
      - "${PERFORMANCE_PORT}:${PERFORMANCE_PORT}"

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    env_file:
      - ./search/.env
    ports:
      - "${SEARCH_PORT}:${SEARCH_PORT}"