apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth
    environment: production
spec:
  type: NodePort # 필요 시 LoadBalancer로 변경 가능
  selector:
    app: auth
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
  externalTrafficPolicy: Local # 외부 요청의 소스 IP 유지
