apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "alb"                     # ALB 사용 설정
    alb.ingress.kubernetes.io/scheme: "internal"           # 외부 노출용 ALB
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]' # HTTP 트래픽 처리
  labels:
    app: backend-ingress
spec:
  rules:
    - host: ticket101.kr
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /favorite
            pathType: Prefix
            backend:
              service:
                name: favorite-service
                port:
                  number: 80
          - path: /performance
            pathType: Prefix
            backend:
              service:
                name: performance-service
                port:
                  number: 80
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 80
          - path: /survey
            pathType: Prefix
            backend:
              service:
                name: survey-service
                port:
                  number: 80
